name:                my-haskell-lambda
version:             0.1.0
github:              "githubuser/my-haskell-lambda"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

description:         Please see the README on GitHub at <https://github.com/githubuser/my-haskell-lambda#readme>

dependencies:
- base >= 4.7 && < 5
- aws-lambda-haskell-runtime >= 3.0.0
- aeson
- text
- amazonka-dynamodb
- amazonka
- bytestring
- lens
- resourcet
- unordered-containers
- monad-control
- unliftio-core

# ghc-options: -O2 -static -threaded
# cc-options: -static
# ld-options: -static -pthread

library:
  source-dirs: src

executables:
  bootstrap:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - my-haskell-lambda

default-extensions:
  - RecordWildCards
  - OverloadedLists
  - OverloadedStrings
  - DeriveGeneric
